name: clone lushunming/AndroidCatVodSpider

on:
  #push:
  #  branches: [ "multiThread" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'jetbrains'
        #cache: gradle
        
    - name: Clone project
      run: |
        rm -rf app gradle jar json tools
        git clone --recurse-submodules https://github.com/lushunming/AndroidCatVodSpider ./
        #cp -rf ./project/* ./
        #rm -rf ./project
        cp -rf ./Myspider/* ./app/src/main/java/com/github/catvod/spider/

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.4
      with:
        default_author: github_actions
        message: 'update from lushunming/AndroidCatVodSpider'
        add: "['./*']"

