name: Spider Jar Gen CI

on:
  #push:
  #  branches: [ "multiThread" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'jetbrains'
        cache: gradle
        
    - name: Grant execute permission to gradlew
      run: |
        chmod +x ./gradlew
        cp -rf ./Myspider/*.java ./app/src/main/java/com/github/catvod/spider/
        cp -rf ./Myspider/tools/* ./app/src/main/java/com/github/catvod/spider/tools/
        rm -rf ./app/src/main/java/com/github/catvod/spider/miss.java
        rm -rf ./app/src/main/java/com/github/catvod/spider/miss.java
      

    - name: Build with Gradle
      run: ./gradlew app:buildCustomSpiderJar
        

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.4
      with:
        default_author: github_actions
        message: 'update spider'
        add: "['./jar/custom_spider.jar', './jar/custom_spider.jar.md5']"
